### ISSUE TITLE
command parsing is not woking

### ISSUE THREAD

**Issue by vishnumishra** [outbounder/angelscripts-cellcmds#2]
Hi,

I created a new project and using the cellcmds.

cell.json 

`  "name": "deployment",`
`  "remote": " ssh ubuntu@myserverIp", `
`  "nodeVersion": "6.3.*", `
  `"cwd": "~/deployment",`
 ` "main": "index.js",`
 ` "source": "https://github.com/somerepo/deployment.git",`
 ` "branch": "master",`
 ` "myName":"Vishnu Mishra",`
 ` "origin": "origin",`
 ` "test":"echo {myName}"`

I'm running the command : 
`node ./node_modules/.bin/angel cell test ./dna/_production/cell.json`

It should print `Vishnu Mishra` but I'm getting `{myName}`

**Comment by outbounder** [comment]
@vishnumishra Hi there,

I guess you're using cellcmds v1.2.0 which internally uses [organic-dna-loader](https://github.com/outbounder/organic-dna-loader) -> [organic-dna-resolve](https://github.com/camplight/organic-dna-resolve)

ie cell.json is parsed as DNA structure and doesn't uses *old* pre 1.2.0 plain json format (that is done to be able to use DNA reference features & etc.).

So to make it work your cell.json's test command should be as follows:

```
{
  ...
  "test":"echo &{myName}"
}
```

I guess that this confusion came from outdated README (which I'm updating atm to latest version). 
Let me know if that resolves the issue or do you have any other related questions ;)

**Comment by vishnumishra** [comment]
👍 

"test":"echo &{myName}"

'&' Did the work
thanks
